### ISSUE TITLE
Provide branding for other products

### ISSUE THREAD

**Issue by Panthro** [AdaptiveMe/adaptive-ide-products#2]
please provide the branding modules inside the folder "branding"

**Comment by carloslozano** [comment]
You can add specific config files as you advance with the build of the different IDEs.

**Comment by Panthro** [comment]
perfect, the artwork was all I needed.

**Comment by carloslozano** [comment]
I've created issues #3 , #4 , #5, #6 and #7 for the different ide's and one for the common plugin modules. 

Three things I wanted to comment:
1. I think we should have all the IDEs as modules of a gradle project, each with their own gradle build.
2. I think we should move the branding inside each of these suggested IDE modules.
3. As mentioned in #7, this should be the module with ALL the plugins - modules #3, #4, #5 and #6 would use these plugins respectively.

Anyway, next time we catch-up we can define specifics. This is food for thought in the meantime.
